### ISSUE TITLE
JsonRowWriteStream throws exception if there's nothing to write

### ISSUE THREAD

**Issue by bestit-el-bardan** [spryker-middleware/process#49]
When using the JsonRowWriteStream in a middleware pipeline which writes nothing (i.e. if it's a delta import where there is nothing to import), it throws an exception.

The problem is that `ftruncate` is always called, even when the file size is 0 which leads to the following:

```
if ($this->handle) {
    $this->flush();
    $stat = fstat($this->handle);
    ftruncate($this->handle, $stat[static::KEY_SIZE] - 1);

    return fclose($this->handle);
}
```

`$stat[static::KEY_SIZE] - 1` => -1 because the file size is 0 and `ftruncate` throws an error because it can't handle a negative size.

```
ErrorException - Exception: ftruncate(): Negative size is not supported
in /data/shop/development/current/vendor/spryker-middleware/process/src/SprykerMiddleware/Zed/Process/Business/Stream/JsonRowWriteStream.php (84)
```

**Comment by tvaleriy** [comment]
Internal ticket is created. I'm closing this ticket here.
