### ISSUE TITLE
Monolog\Handler\HandlerInterface added the public function close(): void 

### ISSUE THREAD

**Issue by bestit-franz** [spryker-middleware/process#54]
* The dependency to the monolog handler is completly missing in the composer.json. 
* The latest version of the implemented Interface of Pyz\Zed\Process\Communication\Plugin\Handler\StdErrStreamHandlerPlugin is now missing the abstract close method

**Comment by tvaleriy** [comment]
Hi @bestit-franz, thank you for reporting these problems.
I created an internal ticket for our development and will update you here when there is a new version.

In the meantime could you say about your priorities here? Is the project blocked due to these problems?

Best,
Spryker Support Team

**Comment by bestit-franz** [comment]
Thanks for the fast reply. The project is not affected because we were able to add the class to our project namespace. But after the update we want to delete it to benefit from future updates.

**Comment by tvaleriy** [comment]
It seems that this should have been fixed already in https://github.com/spryker/log/compare/3.8.0...3.8.1.
Could you please update mentioned module?

Best,
Spryker Support Team

**Comment by bestit-franz** [comment]
https://github.com/spryker-middleware/process/blob/569954b4644d879a2c1b99f23eaca3afb7863adf/src/SprykerMiddleware/Zed/Process/Dependency/Plugin/Log/MiddlewareLogHandlerPluginInterface.php#L10
I don't hink that this would solve the problem as the `MiddlewareLogHandlerPluginInterface` uses the HandlerInterface from Monolog namespace and not from Spryker and it would still be missing in composer.json.

**Comment by dereuromark** [comment]
> The dependency to the monolog handler is completly missing in the composer.json.

That is not quite true, as you can find out by composer pulling the dependencies.
This package indirectly requires spryker/log, which then requires spryker/monolog:
https://github.com/spryker/monolog/blob/master/composer.json#L7 again then requires `"monolog/monolog": "^1.21.0 || ^2.0.0"`
So the dependency to one of those majors is present.

The question is if that is enough on its own.

**Comment by tvaleriy** [comment]
Thanks for additional clarification @bestit-franz, you are right. As I said, I'll update you once it's fixed.

Best,
Spryker Support Team

**Comment by tvaleriy** [comment]
Hi @bestit-franz, 
this should have been fixed in https://github.com/spryker-middleware/process/releases/tag/1.2.0.

Have a nice evening and stay safe these days!

Best,
Spryker Support Team
